### ISSUE TITLE
DNS challenge for anagraph.org & ephemere.org

### ISSUE THREAD

**Issue by Nayte91** [Nayte91/traefik-reverse-proxy#3]
- Use docker secret, 
- replace HTTP challenge,
- close port 80,

From [traefik user guide](https://doc.traefik.io/traefik/user-guides/docker-compose/acme-dns/)
From [traefik documentation](https://doc.traefik.io/traefik/https/acme/#dnschallenge)
From [let's encrypt documentation](https://letsencrypt.org/docs/challenge-types/)
[Deep dive into DNS challenge](https://www.eff.org/deeplinks/2018/02/technical-deep-dive-securing-automation-acme-dns-challenge-validation)
From chatGPT:

1. OVH Side:
a. Obtain OVH API Credentials:
Log in to your OVH account.
Navigate to the "API" section in the OVH Control Panel.
Create an API application, note the application key, application secret, and consumer key.
2. Docker Secrets:
a. Create Docker Secrets:
Run the following commands to create Docker secrets for OVH credentials and basic authentication:
```bash
# OVH Credentials
echo "your_ovh_app_key" | docker secret create ovh_app_key -
echo "your_ovh_app_secret" | docker secret create ovh_app_secret -
echo "your_ovh_consumer_key" | docker secret create ovh_consumer_key -

# Basic Authentication Password (htpasswd)
htpasswd -nbB your_username your_password | docker secret create htpasswd -
```
3. Updated docker-compose.yml:
```yaml
version: "3.8"

services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      - "--configFile=/traefik.yml"
    ports:
      - "443:443"
    secrets:
      - ovh_app_key
      - ovh_app_secret
      - ovh_consumer_key
      - htpasswd
    environment:
      - OVH_ENDPOINT=ovh-eu

secrets:
  ovh_app_key:
    external: true
  ovh_app_secret:
    external: true
  ovh_consumer_key:
    external: true
  htpasswd:
    external: true

networks:
  default:
    external:
      name: "web"
```
4. Updated traefik.yml:
```yaml
api:
  dashboard: true
  insecure: false

entryPoints:
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt: #can rename from actual leresolver?
    acme: #can be with the domain name e.g. anagraph?
      email: your_email@example.com
      storage: acme.json #can rename to anagraph.json?
      dnsChallenge:
        provider: ovh
        ovh:
          endpoint: "ovh-eu"
          applicationKeyFile: "/run/secrets/ovh_app_key"
          applicationSecretFile: "/run/secrets/ovh_app_secret"
          consumerKeyFile: "/run/secrets/ovh_consumer_key"
 
http:
  routers:
    traefik:
      rule: "Host(`traefik.anagraph.org`)"
      entryPoints:
        - websecure
      service: api@internal
      middlewares:
        - traefik-auth

  middlewares:
    traefik-auth:
      basicAuth:
        usersFile: "/run/secrets/htpasswd"
```
